[build]
  command = "npm run build"
  publish = "dist/sadhana-report/browser"

[dev]
  framework = "#custom"
  command = "npm start"
  targetPort = 4200
  port = 8888

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
