import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';

// Parse .env file if present (local dev)
const fromFile = {};
if (existsSync('.env')) {
  for (const line of readFileSync('.env', 'utf8').split('\n')) {
    const m = /^([A-Z_][A-Z0-9_]*)=(.*)$/.exec(line.trim());
    if (m) fromFile[m[1]] = m[2].replace(/^["']|["']$/g, '');
  }
}

const get = (k) => process.env[k] || fromFile[k] || '';

const firebase = {
  apiKey:            get('FIREBASE_API_KEY'),
  authDomain:        get('FIREBASE_AUTH_DOMAIN'),
  projectId:         get('FIREBASE_PROJECT_ID'),
  storageBucket:     get('FIREBASE_STORAGE_BUCKET'),
  messagingSenderId: get('FIREBASE_MESSAGING_SENDER_ID'),
  appId:             get('FIREBASE_APP_ID'),
};

const gen = (prod) => `// Generated by scripts/gen-env.mjs — do not edit manually.
export const environment = {
  production: ${prod},
  firebase: {
    apiKey:            '${firebase.apiKey}',
    authDomain:        '${firebase.authDomain}',
    projectId:         '${firebase.projectId}',
    storageBucket:     '${firebase.storageBucket}',
    messagingSenderId: '${firebase.messagingSenderId}',
    appId:             '${firebase.appId}',
  },
};
`;

mkdirSync('src/environments', { recursive: true });
writeFileSync('src/environments/environment.ts',      gen(false));
writeFileSync('src/environments/environment.prod.ts', gen(true));
console.log('Generated environment files.');
